/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false cloudflare-env.d.ts` (hash: 868a3ea15af9b052c7dad465a79849c4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
		NEXT_PUBLIC_SUPABASE_URL: string;
		SUPABASE_SERVICE_ROLE_KEY: string;
		NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID: string;
		NEXT_PUBLIC_GOOGLE_ADS_SLOT_ID: string;
		NEXT_PUBLIC_MEASUREMENT_ID: string;
		NEXT_PUBLIC_CURRENT_YEAR: string;
		NEXT_PUBLIC_CURRENT_SEM: string;
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
		CLERK_SECRET_KEY: string;
		NEXT_PUBLIC_CLERK_SIGN_IN_URL: string;
		NEXT_PUBLIC_CLERK_SIGN_UP_URL: string;
		NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: string;
		NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: string;
		GTM_ID: string;
		BLOB_READ_WRITE_TOKEN: string;
		IMGUR_CLIENT_ID: string;
		IMGUR_CLIENT_SECRET: string;
		IS_PREENROLLMENT_OPEN: string;
		NEXT_PUBLIC_DATABASE_LAST_UPDATE: string;
		NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
		SUPABASE_SECRET_KEY: string;
		SUPABASE_JWT_SECRET: string;
		UM_IOS_API_SECRET: string;
		WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
		UI_PROFILE: Fetcher /* umeh-ui-profile */;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
