/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false cloudflare-env.d.ts` (hash: 75a7099b0fc6ca1c8ec1f5469c0d4f82)
declare namespace Cloudflare {
	interface Env {
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		NEXT_TAG_CACHE_D1: D1Database;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		NEXT_PUBLIC_SUPABASE_URL: string;
		NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID: string;
		NEXT_PUBLIC_GOOGLE_ADS_SLOT_ID: string;
		NEXT_PUBLIC_MEASUREMENT_ID: string;
		NEXT_PUBLIC_CURRENT_YEAR: string;
		NEXT_PUBLIC_CURRENT_SEM: string;
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
		CLERK_SECRET_KEY: string;
		NEXT_PUBLIC_CLERK_SIGN_IN_URL: string;
		NEXT_PUBLIC_CLERK_SIGN_UP_URL: string;
		NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: string;
		NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: string;
		GTM_ID: string;
		BLOB_READ_WRITE_TOKEN: string;
		IMGUR_CLIENT_ID: string;
		IMGUR_CLIENT_SECRET: string;
		IS_PREENROLLMENT_OPEN: string;
		NEXT_PUBLIC_DATABASE_LAST_UPDATE: string;
		NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
		SUPABASE_SECRET_KEY: string;
		UM_IOS_API_SECRET: string;
		TELEGRAM_REPORT_CHAT_ID: string;
		TELEGRAM_BOT_TOKEN: string;
		UM_OPEN_DATA_TOKEN: string;
		PLATFORM_ADMIN_USER_IDS: string;
		SUPABASE_DB_URL: string;
		PLATFORM_ADMIN_EMAILS: string;
		TELEGRAM_API_BASE_URL: string;
		TELEGRAM_REPORT_THREAD_ID: string;
		UM_IOS_MIN_SUPPORTED_VERSION: string;
		UM_IOS_LATEST_VERSION: string;
		UM_IOS_UPDATE_URL: string;
		WORKER_SELF_REFERENCE: Fetcher /* next-web */;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
