import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { inflateSync } from "node:zlib";

import { describe, expect, it } from "vitest";

import buildManifest from "@/app/manifest";

/**
 * Root icon assets (browser tab + iOS home screen + web app manifest).
 *
 * These are generated by `npm run icons:build`
 * (scripts/build-brand-icons.mjs) from the shared brand mark: the lucide "cat"
 * glyph (ISC) that the companion iOS app renders through `CatLogo`
 * (`cat-blue.svg`, stroke `#003DB8`), kept licensed in this repository as
 * `design/cat-logo.svg`. Nothing here upscales a bitmap: the previous
 * `public/favicon.png` was a 24×24 raster and is no longer referenced.
 *
 * `/favicon.ico`, `/apple-touch-icon.png` and `/apple-touch-icon-precomposed.png`
 * live at the site root because iOS Safari and legacy crawlers request those
 * exact paths with no `<link>` tag to guide them. The `public/icon/*.png` set
 * replaces the retired 72…512 JPEG rasters that `app/manifest.ts` used to list.
 */

const PUBLIC_DIR = join(process.cwd(), "public");
const LAYOUT = join(process.cwd(), "app", "layout.tsx");

const BRAND_BLUE = [0, 61, 184];
const BRAND_NAVY = [12, 32, 70];
/** iOS AppIcon light/dark glyphs put their ink on 56.2% of the canvas. */
const IOS_INK_FRACTION = 0.562;

const hex = (rgb: number[]) =>
  `#${rgb.map((value) => value.toString(16).padStart(2, "0").toUpperCase()).join("")}`;

const read = (file: string) => readFileSync(join(PUBLIC_DIR, file));

function paeth(a: number, b: number, c: number) {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  return pb <= pc ? b : c;
}

/** Decodes an 8-bit non-interlaced RGBA PNG (the only shape sharp emits here). */
function decodePng(buffer: Buffer) {
  expect(buffer.subarray(0, 8).toString("hex"), "not a PNG").toBe("89504e470d0a1a0a");
  const width = buffer.readUInt32BE(16);
  const height = buffer.readUInt32BE(20);
  expect(buffer[24], "bit depth").toBe(8);
  expect(buffer[25], "colour type").toBe(6);
  expect(buffer[28], "interlace").toBe(0);

  const idat: Buffer[] = [];
  let offset = 8;
  while (offset + 8 <= buffer.length) {
    const length = buffer.readUInt32BE(offset);
    const type = buffer.subarray(offset + 4, offset + 8).toString("ascii");
    if (type === "IDAT") idat.push(buffer.subarray(offset + 8, offset + 8 + length));
    if (type === "IEND") break;
    offset += 12 + length;
  }

  const raw = inflateSync(Buffer.concat(idat));
  const bpp = 4;
  const stride = width * bpp;
  const data = Buffer.alloc(height * stride);
  for (let y = 0; y < height; y += 1) {
    const filter = raw[y * (stride + 1)];
    const row = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    const line = data.subarray(y * stride, (y + 1) * stride);
    const prior =
      y === 0 ? Buffer.alloc(stride) : data.subarray((y - 1) * stride, y * stride);
    for (let x = 0; x < stride; x += 1) {
      const a = x >= bpp ? line[x - bpp] : 0;
      const b = prior[x];
      const c = x >= bpp ? prior[x - bpp] : 0;
      const value = row[x];
      line[x] =
        filter === 0
          ? value
          : filter === 1
            ? (value + a) & 0xff
            : filter === 2
              ? (value + b) & 0xff
              : filter === 3
                ? (value + ((a + b) >> 1)) & 0xff
                : (value + paeth(a, b, c)) & 0xff;
    }
  }

  return { width, height, data };
}

type Pixel = [number, number, number, number];

function pixelAt(image: ReturnType<typeof decodePng>, x: number, y: number): Pixel {
  const at = (y * image.width + x) * 4;
  return [
    image.data[at],
    image.data[at + 1],
    image.data[at + 2],
    image.data[at + 3],
  ];
}

/** Ink = anything far enough from the background to be glyph, not antialiasing. */
function inkBounds(image: ReturnType<typeof decodePng>, background: number[]) {
  let minX = image.width;
  let minY = image.height;
  let maxX = -1;
  let maxY = -1;
  for (let y = 0; y < image.height; y += 1) {
    for (let x = 0; x < image.width; x += 1) {
      const [r, g, b] = pixelAt(image, x, y);
      const distance =
        Math.abs(r - background[0]) + Math.abs(g - background[1]) + Math.abs(b - background[2]);
      if (distance <= 60) continue;
      minX = Math.min(minX, x);
      minY = Math.min(minY, y);
      maxX = Math.max(maxX, x);
      maxY = Math.max(maxY, y);
    }
  }
  return { minX, minY, maxX, maxY, width: maxX - minX + 1, height: maxY - minY + 1 };
}

function countWhere(
  image: ReturnType<typeof decodePng>,
  predicate: (pixel: Pixel) => boolean,
) {
  let count = 0;
  for (let y = 0; y < image.height; y += 1) {
    for (let x = 0; x < image.width; x += 1) {
      if (predicate(pixelAt(image, x, y))) count += 1;
    }
  }
  return count;
}

const isBrandBlue = ([r, g, b, a]: Pixel) => a === 255 && r === 0 && g === 61 && b === 184;
/** Any pixel the blue glyph owns, antialiasing included. */
const isBlueInk = ([r, , b, a]: Pixel) => a === 255 && b > 120 && r < 120;

/** Distance from the icon centre to the farthest glyph pixel, in edge fractions. */
function farthestInkRadius(image: ReturnType<typeof decodePng>, background: number[]) {
  const centre = image.width / 2;
  let farthest = 0;
  for (let y = 0; y < image.height; y += 1) {
    for (let x = 0; x < image.width; x += 1) {
      const [r, g, b] = pixelAt(image, x, y);
      const distance =
        Math.abs(r - background[0]) + Math.abs(g - background[1]) + Math.abs(b - background[2]);
      if (distance <= 60) continue;
      farthest = Math.max(farthest, Math.hypot(x + 0.5 - centre, y + 0.5 - centre));
    }
  }
  return farthest / image.width;
}

interface IcoEntry {
  size: number;
  bitCount: number;
  offset: number;
  length: number;
  payload: Buffer;
}

function parseIco(buffer: Buffer): IcoEntry[] {
  expect(buffer.readUInt16LE(0), "ICO reserved field").toBe(0);
  expect(buffer.readUInt16LE(2), "ICO type (1 = icon)").toBe(1);
  const count = buffer.readUInt16LE(4);
  const entries: IcoEntry[] = [];
  for (let index = 0; index < count; index += 1) {
    const at = 6 + index * 16;
    const size = buffer[at] || 256;
    expect(buffer[at + 1] || 256, "ICO entry must be square").toBe(size);
    const length = buffer.readUInt32LE(at + 8);
    const offset = buffer.readUInt32LE(at + 12);
    const payload = buffer.subarray(offset, offset + length);

    // BITMAPINFOHEADER: biHeight doubles up the XOR bitmap and the AND mask.
    expect(payload.readUInt32LE(0), "biSize").toBe(40);
    expect(payload.readInt32LE(4), "biWidth").toBe(size);
    expect(payload.readInt32LE(8), "biHeight").toBe(size * 2);
    expect(payload.readUInt16LE(14), "biBitCount").toBe(32);
    expect(payload.length, "BMP icon size").toBe(
      40 + size * size * 4 + Math.ceil(size / 32) * 4 * size,
    );

    entries.push({ size, bitCount: buffer.readUInt16LE(at + 6), offset, length, payload });
  }
  return entries;
}

/** Reads a 32bpp BMP icon entry back into top-down RGBA. */
function decodeIcoEntry(entry: IcoEntry) {
  const { size } = entry;
  const data = Buffer.alloc(size * size * 4);
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const from = 40 + (((size - 1 - y) * size + x) * 4);
      const to = (y * size + x) * 4;
      data[to] = entry.payload[from + 2];
      data[to + 1] = entry.payload[from + 1];
      data[to + 2] = entry.payload[from];
      data[to + 3] = entry.payload[from + 3];
    }
  }
  return { width: size, height: size, data };
}

describe("root icon assets", () => {
  it("ships the paths iOS and legacy crawlers request without a link tag", () => {
    for (const file of [
      "favicon.ico",
      "favicon.svg",
      "favicon-dark.svg",
      "apple-touch-icon.png",
      "apple-touch-icon-precomposed.png",
    ]) {
      expect(read(file).byteLength, `${file} must not be empty`).toBeGreaterThan(0);
    }
  });

  it("packs 16/32/48 BMP entries into favicon.ico", () => {
    const ico = read("favicon.ico");
    const entries = parseIco(ico);
    expect(entries.map((entry) => entry.size)).toEqual([16, 32, 48]);
    expect(entries.every((entry) => entry.bitCount === 32)).toBe(true);

    let expectedOffset = 6 + entries.length * 16;
    for (const entry of entries) {
      expect(entry.length).toBeGreaterThan(0);
      expect(entry.offset, "entries must be packed back to back").toBe(expectedOffset);
      expectedOffset += entry.length;
    }
    expect(expectedOffset, "entries must fill the file exactly").toBe(ico.byteLength);
  });

  it("keeps the small favicon legible instead of falling back to a bitmap", () => {
    const smallest = parseIco(read("favicon.ico"))[0];
    expect(smallest.size).toBe(16);
    const image = decodeIcoEntry(smallest);

    // Rounded corners are transparent, the tile is white, and the glyph is the
    // iOS brand blue: proof the file is a rendered vector, not an upscale.
    expect(pixelAt(image, 0, 0)[3]).toBeLessThan(128);
    expect(pixelAt(image, 8, 7)).toEqual([255, 255, 255, 255]);
    // ~13px of glyph in a 16px tile; at this size most ink is antialiased, so
    // count blue-dominant pixels rather than exact brand-blue ones.
    expect(countWhere(image, isBlueInk)).toBeGreaterThan(20);
    expect(countWhere(image, isBlueInk)).toBeLessThan(80);
  });
});

describe("apple-touch-icon", () => {
  it("ships a 180×180 opaque square so iOS can apply its own mask", () => {
    const icon = read("apple-touch-icon.png");
    const image = decodePng(icon);
    expect(image.width).toBe(180);
    expect(image.height).toBe(180);

    // Transparency would composite on black behind iOS's squircle, and a baked
    // radius would nest a rounded corner inside a rounded corner.
    expect(pixelAt(image, 0, 0)).toEqual([255, 255, 255, 255]);
    for (let y = 0; y < image.height; y += 1) {
      for (let x = 0; x < image.width; x += 1) {
        expect(pixelAt(image, x, y)[3], `alpha at ${x},${y}`).toBe(255);
      }
    }
    expect(countWhere(image, isBrandBlue)).toBeGreaterThan(1000);
  });

  it("uses the same framing as the iOS AppIcon light master", () => {
    const image = decodePng(read("apple-touch-icon.png"));
    const ink = inkBounds(image, [255, 255, 255]);
    expect(ink.width / image.width).toBeCloseTo(IOS_INK_FRACTION, 1);
    expect(ink.height / image.height).toBeCloseTo(IOS_INK_FRACTION, 1);
  });

  it("keeps the legacy -precomposed twin byte-identical", () => {
    expect(read("apple-touch-icon-precomposed.png").equals(read("apple-touch-icon.png"))).toBe(true);
  });
});

describe("vector favicons", () => {
  const source = readFileSync(join(process.cwd(), "design", "cat-logo.svg"), "utf8");
  const glyphPaths = [...source.matchAll(/<path\s+d="([^"]+)"\s*\/>/g)].map((match) => match[1]);

  it("renders the licensed source geometry unchanged", () => {
    expect(glyphPaths.length).toBeGreaterThan(0);
    for (const file of ["favicon.svg", "favicon-dark.svg"]) {
      const svg = read(file).toString("utf8");
      expect(svg, `${file} must credit the ISC source`).toContain("lucide-static");
      for (const d of glyphPaths) {
        expect(svg, `${file} is missing glyph path ${d.slice(0, 16)}…`).toContain(d);
      }
    }
  });

  it("pairs the AppIcon light and dark treatments", () => {
    const light = read("favicon.svg").toString("utf8");
    const dark = read("favicon-dark.svg").toString("utf8");
    expect(light).toContain(`fill="${hex([255, 255, 255])}"`);
    expect(light).toContain(`stroke="${hex(BRAND_BLUE)}"`);
    expect(dark).toContain(`fill="${hex(BRAND_NAVY)}"`);
    expect(dark).toContain(`stroke="${hex([255, 255, 255])}"`);
    // A rounded tile, because nothing masks a favicon in a tab strip.
    expect(light).toMatch(/rx="[1-9]/);
    expect(dark).toMatch(/rx="[1-9]/);
  });
});

describe("web app manifest icons", () => {
  const manifest = buildManifest();
  const icons = manifest.icons ?? [];

  it("advertises PNG icons that actually exist", () => {
    expect(icons.length).toBeGreaterThan(0);
    for (const icon of icons) {
      expect(icon.src, "manifest icon src").toMatch(/^\/icon\/.+\.png$/);
      expect(icon.type).toBe("image/png");
      const file = join(PUBLIC_DIR, (icon.src as string).replace(/^\//, ""));
      expect(existsSync(file), `${icon.src} is missing from public/`).toBe(true);

      const image = decodePng(readFileSync(file));
      expect(`${image.width}x${image.height}`, `${icon.src} size`).toBe(icon.sizes);
    }
  });

  it("ships the 192/512 sizes Chrome needs to offer installation", () => {
    expect(icons.map((icon) => `${icon.sizes}:${icon.purpose}`).sort()).toEqual([
      "192x192:any",
      "512x512:any",
      "512x512:maskable",
    ]);
  });

  it("keeps the maskable mark inside Android's safe zone", () => {
    expect(icons.some((icon) => icon.purpose === "maskable")).toBe(true);
    const image = decodePng(readFileSync(join(PUBLIC_DIR, "icon", "maskable-512.png")));

    // Android crops to a circle of 80% diameter, so the tile must be full-bleed
    // and the glyph must stay inside that 40%-of-the-edge safe radius.
    expect(pixelAt(image, 0, 0)).toEqual([255, 255, 255, 255]);
    expect(farthestInkRadius(image, [255, 255, 255])).toBeLessThan(0.4);
  });

  it("retires the old JPEG raster set and the dead bitmaps", () => {
    expect(readdirSync(join(PUBLIC_DIR, "icon")).sort()).toEqual([
      "192.png",
      "512.png",
      "maskable-512.png",
    ]);
    for (const file of ["favicon.png", "whole-icon.png"]) {
      expect(existsSync(join(PUBLIC_DIR, file)), `public/${file} should be gone`).toBe(false);
    }
  });
});

describe("layout head links", () => {
  const layout = readFileSync(LAYOUT, "utf8");

  it("points the head at the generated icons", () => {
    expect(layout).toContain('href="/favicon.ico"');
    expect(layout).toContain('href="/favicon.svg"');
    expect(layout).toContain('href="/favicon-dark.svg"');
    expect(layout).toContain('media="(prefers-color-scheme: dark)"');
    expect(layout).toContain('rel="apple-touch-icon"');
    expect(layout).toContain('href="/apple-touch-icon.png"');
    expect(layout).toContain('rel="apple-touch-icon-precomposed"');
    expect(layout).toContain('href="/apple-touch-icon-precomposed.png"');
  });

  it("leaves the manifest link to Next instead of writing it twice", () => {
    // `app/manifest.ts` already makes Next inject <link rel="manifest">; the
    // hand-written copy used to be emitted a second time.
    expect(layout).not.toContain('rel="manifest"');
    expect(layout).not.toContain("favicon.png");
  });
});
